require './project_files/book'
require './project_files/classroom'
require './project_files/person'
require './project_files/teacher'
require './project_files/student'
require './project_files/rental'
require './project_files/capitalize'
require './project_files/trimmer'
